Repository 2025TUKCOMCD/JZP, pull requests merged in 2025-01, with the labels that each got.

#22 [Feat] 1차 필터
  AI/README.txt
  AI/__pycache__/filter_1_cam.cpython-312.pyc
  AI/capture_data/0README.txt
  AI/filter_1.py
  AI/filter_1_cam.py
  AI/frame_test.py
  AI/main.py
Labels: 🤖 AI

#62 feat : view grid
  JZP_FE/.prettierrc
  JZP_FE/index.html
  JZP_FE/package-lock.json
  JZP_FE/package.json
  JZP_FE/postcss.config.js
  JZP_FE/src/App.jsx
  JZP_FE/src/index.css
  JZP_FE/src/pages/HomePage.jsx
  JZP_FE/src/pages/JuniorMainPage.jsx
  JZP_FE/src/pages/SeniorMainPage.jsx
  JZP_FE/tailwind.config.js
Labels: ✨Feature, ⚙️ Setting

#64 Feat/main page
  JZP_FE/src/App.jsx
  JZP_FE/src/assets/icons/ticketIcon.svg
  JZP_FE/src/assets/icons/ticketPrintIcon.svg
  JZP_FE/src/pages/HomePage.jsx
  JZP_FE/src/pages/JuniorMainPage.jsx
  JZP_FE/src/pages/JuniorMovieSelectPage.jsx
  JZP_FE/src/pages/SeniorMainPage.jsx
  JZP_FE/src/pages/SeniorMovieSelectPage.jsx
Labels: ✨Feature, 🎨 HTML&CSS

#66 Feat : movie select
  JZP_FE/public/fonts/SB 어그로 B.woff
  JZP_FE/public/fonts/SB 어그로 L.woff
  JZP_FE/public/fonts/SB 어그로 M.woff
  JZP_FE/src/App.jsx
  JZP_FE/src/assets/icons/homeIcon.svg
  JZP_FE/src/assets/icons/theDayAfter.svg
  JZP_FE/src/assets/icons/theDayBefore.svg
  JZP_FE/src/assets/images/12.png
  JZP_FE/src/assets/images/15.png
  JZP_FE/src/assets/images/18.png
  JZP_FE/src/assets/images/ALL.png
  JZP_FE/src/assets/images/movie1.png
  JZP_FE/src/assets/images/movie2.png
  JZP_FE/src/assets/images/movie3.png
  JZP_FE/src/assets/images/movie4.png
  JZP_FE/src/components/MovieStepBar.jsx
  JZP_FE/src/components/dateSelectBar.jsx
  JZP_FE/src/components/dateSelectBar2.jsx
  JZP_FE/src/components/header.jsx
  JZP_FE/src/index.css
  JZP_FE/src/pages/HomePage.jsx
  JZP_FE/src/pages/JuniorBookingHistoryPage.jsx
  JZP_FE/src/pages/JuniorMainPage.jsx
  JZP_FE/src/pages/JuniorMovieSelectPage.jsx
  JZP_FE/src/pages/JuniorPayPage.jsx
  JZP_FE/src/pages/JuniorSeatSelectPage.jsx
  JZP_FE/src/pages/SeniorBookingHistoryPage.jsx
  JZP_FE/src/pages/SeniorMainPage.jsx
  JZP_FE/src/pages/SeniorMovieSelectPage.jsx
  JZP_FE/src/pages/SeniorPayPage.jsx
  JZP_FE/src/pages/SeniorSeatSelectPage.jsx
  JZP_FE/tailwind.config.js
Labels: ✨Feature, 🎨 HTML&CSS, 🛠️ Refactor

#71 [Setting] : docker 연동 및 EC2 배포
  JZP_BE/jzp/Dockerfile
  JZP_BE/jzp/src/main/resources/application.properties
Labels: ⚙️ Setting

#73 Feat/pay page
  JZP_FE/src/assets/images/kakaopay.png
  JZP_FE/src/components/Pay.jsx
  JZP_FE/src/components/Pay2.jsx
  JZP_FE/src/pages/JuniorPayPage.jsx
  JZP_FE/src/pages/SeniorPayPage.jsx
  JZP_FE/tailwind.config.js
Labels: ✨Feature, 🎨 HTML&CSS

#88 feat:영화 불러오기
  JZP_BE/jzp/src/main/java/com/example/jzp/controller/MovieController.java
  JZP_BE/jzp/src/main/java/com/example/jzp/model/Movie.java
  JZP_BE/jzp/src/main/java/com/example/jzp/repository/MovieRepository.java
  JZP_BE/jzp/src/main/java/com/example/jzp/service/MovieService.java
Labels: ✨Feature

#98 PAT test
  aaa.txt
Labels: ✅ Test

#99 feat : 영화 선택 및 시간 지정
  .idea/modules.xml
  JZP_BE/jzp/src/main/java/com/example/jzp/controller/MovieController.java
  JZP_BE/jzp/src/main/java/com/example/jzp/model/Movie.java
  JZP_BE/jzp/src/main/java/com/example/jzp/repository/MovieRepository.java
  JZP_BE/jzp/src/main/java/com/example/jzp/service/MovieService.java
  JZP_BE/jzp/src/main/resources/application.properties
Labels: ✨Feature

#103 Feat/movie customer
  JZP_BE/jzp/src/main/java/com/example/jzp/controller/MovieController.java
  JZP_BE/jzp/src/main/java/com/example/jzp/model/Movie.java
  JZP_BE/jzp/src/main/java/com/example/jzp/model/Ticket.java
  JZP_BE/jzp/src/main/java/com/example/jzp/repository/TicketRepository.java
  JZP_BE/jzp/src/main/java/com/example/jzp/service/MovieService.java
  JZP_BE/jzp/src/main/java/com/example/jzp/service/TicketService.java
  JZP_BE/jzp/src/main/resources/application.properties
Labels: ✨Feature
