Repository 2025TUKCOMCD/JZP, pull requests merged in 2025-02, with the labels that each got.

#105 Feat/payment
  .idea/modules/jzp.iml
  JZP_BE/jzp/build.gradle
  JZP_BE/jzp/src/main/java/com/example/jzp/controller/MovieController.java
  JZP_BE/jzp/src/main/java/com/example/jzp/model/Movie.java
  JZP_BE/jzp/src/main/java/com/example/jzp/service/MovieService.java
Labels: 🐞 BugFix, ✨Feature

#102 Feat/booking history
  JZP_FE/src/App.jsx
  JZP_FE/src/components/BookingCard.jsx
  JZP_FE/src/components/BookingCard2.jsx
  JZP_FE/src/components/Pay.jsx
  JZP_FE/src/components/Pay2.jsx
  JZP_FE/src/pages/JuniorBookingHistoryPage.jsx
  JZP_FE/src/pages/JuniorPayPage.jsx
  JZP_FE/src/pages/JuniorSendingPage.jsx
  JZP_FE/src/pages/SeniorBookingHistoryPage.jsx
  JZP_FE/src/pages/SeniorPayPage.jsx
  JZP_FE/src/pages/SeniorSendingPage.jsx
  JZP_FE/tailwind.config.js
Labels: ✨Feature, 🎨 HTML&CSS

#107 Revert "Feat/payment"
  .idea/modules/jzp.iml
  JZP_BE/jzp/build.gradle
  JZP_BE/jzp/src/main/java/com/example/jzp/controller/MovieController.java
  JZP_BE/jzp/src/main/java/com/example/jzp/model/Movie.java
  JZP_BE/jzp/src/main/java/com/example/jzp/service/MovieService.java
Labels: 🐞 BugFix

#109 fix:bookticket
  JZP_BE/jzp/src/main/java/com/example/jzp/controller/MovieController.java
  JZP_BE/jzp/src/main/java/com/example/jzp/service/MovieService.java
  JZP_BE/jzp/src/main/java/com/example/jzp/service/TicketService.java
  JZP_BE/jzp/src/main/resources/application.properties
Labels: 🐞 BugFix

#110 Feat/movie group
  JZP_BE/jzp/src/main/java/com/example/jzp/controller/MovieController.java
  JZP_BE/jzp/src/main/java/com/example/jzp/model/Movie.java
  JZP_BE/jzp/src/main/java/com/example/jzp/service/MovieService.java
  JZP_BE/jzp/src/main/java/com/example/jzp/service/TicketService.java
  JZP_BE/jzp/src/main/resources/application.properties
Labels: 🐞 BugFix

#111 Feat/movie group
  JZP_BE/jzp/src/main/java/com/example/jzp/controller/MovieController.java
  JZP_BE/jzp/src/main/java/com/example/jzp/model/Movie.java
  JZP_BE/jzp/src/main/java/com/example/jzp/model/Ticket.java
  JZP_BE/jzp/src/main/java/com/example/jzp/repository/MovieRepository.java
  JZP_BE/jzp/src/main/java/com/example/jzp/repository/TicketRepository.java
  JZP_BE/jzp/src/main/java/com/example/jzp/service/MovieService.java
  JZP_BE/jzp/src/main/java/com/example/jzp/service/TicketService.java
  JZP_BE/jzp/src/main/resources/application.properties
Labels: 🐞 BugFix

#114 Fix : movie_seat
  JZP_BE/jzp/src/main/java/com/example/jzp/controller/MovieController.java
  JZP_BE/jzp/src/main/java/com/example/jzp/model/Movie.java
  JZP_BE/jzp/src/main/java/com/example/jzp/repository/TicketRepository.java
  JZP_BE/jzp/src/main/java/com/example/jzp/service/MovieService.java
  JZP_BE/jzp/src/main/resources/application.properties
Labels: 🐞 BugFix

#117 Feat/tmdb 연동
  .idea/modules/jzp.iml
  JZP_BE/jzp/.gitignore
  JZP_BE/jzp/build.gradle
  JZP_BE/jzp/src/.env
  JZP_BE/jzp/src/main/java/com/example/jzp/controller/MovieController.java
  JZP_BE/jzp/src/main/java/com/example/jzp/model/Movie.java
  JZP_BE/jzp/src/main/java/com/example/jzp/model/Ticket.java
  JZP_BE/jzp/src/main/java/com/example/jzp/repository/MovieRepository.java
  JZP_BE/jzp/src/main/java/com/example/jzp/repository/TicketRepository.java
  JZP_BE/jzp/src/main/java/com/example/jzp/service/MovieService.java
  JZP_BE/jzp/src/main/java/com/example/jzp/service/TicketService.java
  JZP_BE/jzp/src/main/resources/application.properties
Labels: ✨Feature
